name = "IRSpectrum"
uuid = "64770784-cb48-482d-a9ec-e8cee3be2319"
authors = ["Teemu JÃ¤rvinen <teemu.j.jarvinen@student.jyu.fi>"]
version = "0.1.1-DEV"

[deps]
FFTW = "7a1cc6ca-52ef-59f5-83cd-3a7055c09341"

[compat]
julia = "1.1"
FFTW = "1"
